baseURL = 'https://qiyuany.github.io/'
languageCode = 'zh-cn'
title = '我的个人博客'
theme = 'PaperMod'

[params]
author = "Qiyuan Yang"
description = "分享技术与生活的个人博客"
keywords = ["技术", "生活", "学习", "编程"]
env = "production"

# theme params
[params.homeInfoParams]
Title = "你好，我是 Qiyuan Yang"
Content = "欢迎来到我的个人博客。这里记录着我的技术学习、项目经验和生活感悟。"

# social icons
[[params.socialIcons]]
name = "github"
url = "https://github.com/QiyuanY"

[[params.socialIcons]]
name = "email"
url = "mailto:qiyuan.yang@example.com"

# analytics
[params.analytics.google]
SiteVerificationTag = ""

[params.profileMode]
enabled = true # needs to be explicitly set
title = "你好，我是 Qiyuan Yang"
subtitle = "欢迎来到我的个人博客"
imageUrl = "profile.jpg"
imageTitle = "Qiyuan Yang"
imageWidth = 120
imageHeight = 120

[menu]
[[menu.main]]
name = "首页"
url = "/"
weight = 1

[[menu.main]]
name = "文章"
url = "/posts/"
weight = 2

[[menu.main]]
name = "关于"
url = "/about/"
weight = 3
